/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.Server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Type implements org.apache.thrift.TEnum {
  PUSH(0),
  POP(1),
  GET(2),
  SHOW(3),
  GET2(4),
  TOP(5);

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Type findByValue(int value) { 
    switch (value) {
      case 0:
        return PUSH;
      case 1:
        return POP;
      case 2:
        return GET;
      case 3:
        return SHOW;
      case 4:
        return GET2;
      case 5:
        return TOP;
      default:
        return null;
    }
  }
}
